github: [metadata]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-org

defaults:
  -
    scope:
            path: ""
            type: "pages"
    values:
            layout: "default"
            math: false
            blog: false
  -
    scope:
            path: ""
            type: "posts"
    values:
            layout: "post"
            blog: true
