baseURL = '//ryleealanza.org/'
languageCode = 'en-us'
title = 'Rylee Alanza Lyman'
theme = 'alanza'
[params]
  navigation = [
  ["Home", "/"],
  ["Research", "/pages/research/"],
  ["Teaching", "/pages/teaching/"],
  ["Other", "/pages/alanza/"],
  ["Blog", "/posts/"]
  ]

[markup]
  [markup.highlight]
    style = 'catppuccin-frappe'