baseURL = '//ryleealanza.org'
languageCode = 'en-us'
title = 'Rylee Alanza Lyman'
theme = 'alanza'
[params]
  navigation = [
  ["Home", "/"],
  ["Research", "/research/"],
  ["Teaching", "/teaching/"],
  ["Other", "/alanza/"],
  ["Blog", "/posts/"]
  ]

[markup]
  [markup.highlight]
    style = 'catppuccin-frappe'